### ISSUE TITLE
Link to sample

### ISSUE THREAD

**Issue by EmilMoe** [chartjs/chartjs-chart-smith#2]
Could you provide a link to an example or an image preview

**Comment by etimberg** [comment]
@EmilMoe here's a live sample: https://jsfiddle.net/ab0wvm01/

I'll try and get something into the readme.

**Comment by sp-edison** [comment]
@etimberg  Live sample does not work.  https://jsfiddle.net/ab0wvm01/

**Comment by BernhardBaumrock** [comment]
any news on a live sample?

**Comment by etimberg** [comment]
I finally got a doc website set up. Sample is up at https://www.chartjs.org/chartjs-chart-smith/examples
